routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'PagesController@root')->name('home');
// 话题列表为首页
Route::get('/', 'TopicsController@index')->name('root');



// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


//user resources
Route::resource('users', 'UsersController', ['only' => ['show', 'edit', 'update']]);

//topics
Route::resource('topics', 'TopicsController', ['only' => ['index', 'create', 'store', 'update', 'edit', 'destroy']]);
//topics show
Route::get('topics/{topic}/{slug?}', 'TopicsController@show')->name('topics.show');
//upload_images
Route::post('upload_image', 'TopicsController@uploadImage')->name('topics.upload_image');

//topics categories
Route::resource('categories', 'CategoriesController', ['only' => ['show']]);

//replies
Route::resource('replies', 'RepliesController', ['only' => ['store', 'destroy']]);

//notifications
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

Route::get('permission-denied', 'PagesController@permissionDenied')->name('permission-denied');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Auth;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Traits\LastActivedAtHelper;
    use Traits\ActiveUserHelper;
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'introduction', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    //通知方法
    use Notifiable {
        notify as protected laravelNotify;
    }
    public function notify($instance)
    {
        // 如果要通知的人是当前用户，就不必通知了！
        if ($this->id == Auth::id()) {
            return;
        }
        $this->increment('notification_count');
        $this->laravelNotify($instance);
    }

    // 清除通知
    public function markAsRead()
    {
        $this->notification_count = 0;
        $this->save();
        $this->unreadNotifications->markAsRead();
    }


    //user hasmany topic
    public function topics()
    {
        return $this->hasMany(Topic::class);
    }

    


    //this models->user_id
    public function isAuthorOf($model)
    {
        return $this->id == $model->user_id;
    }

        //user hasmany reply
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function setPasswordAttribute($value)
    {
        // 如果值的长度等于 60，即认为是已经做过加密的情况
        if (strlen($value) != 60) {

            // 不等于 60，做密码加密处理
            $value = bcrypt($value);
        }

        $this->attributes['password'] = $value;
    }

    public function setAvatarAttribute($path)
    {
        // 如果不是 `http` 子串开头，那就是从后台上传的，需要补全 URL
        if ( ! starts_with($path, 'http')) {

            // 拼接完整的 URL
            $path = config('app.url') . "/uploads/images/avatars/$path";
        }

        $this->attributes['avatar'] = $path;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\UserRequest;
use App\Handlers\ImageUploadHandler;

class UsersController extends Controller
{
    //middleware过滤
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
    }

    public 	function show(User $user)
    {
    	return view('users.show', compact('user'));
    }


    public function edit(User $user)
    {
        //授权决策
        $this->authorize('update', $user);

    	return view('users.edit', compact('user'));
}

    public function update(UserRequest $request, ImageUploadHandler $uploader, User $user)
    {
        //授权决策
        $this->authorize('update', $user);

        $data = $request->all();

        if ($request->avatar) {
            $result = $uploader->save($request->avatar, 'avatars', $user->id, 362);
            if ($result) {
                $data['avatar'] = $result['path'];
            }
        }

    	$user->update($data);
        return redirect()->route('users.show', $user->id)->with('success', '个人资料编辑成功！');
    }
}

resources/views/users/_replies.blade.php
@if (count($replies))
	<div class="list-group"> 
		@foreach ($replies as $reply)
			<li class="list-group-item">
				<a href="{{ $reply->topic->link(['#reply' . $reply->id]) }}">
					{{ $reply->topic->title }}
				</a>

				<div class="reply-content" style="margin: 6px 0;">
	                {!! $reply->content !!}
	            </div>

	            <div class="meta">
	                <span class="glyphicon glyphicon-time" aria-hidden="true"></span> 
	                回复于 {{ $reply->created_at->diffForHumans() }}
	            </div>
			</li>

		@endforeach
	</div>
@else
	<div class="empty-block">暂无数据 ~_~ </div>
@endif


{{-- 分页 --}}
{!! $replies->appends(Request::except('page'))->render() !!}

resources/views/users/_topics.blade.php
@if (count($topics))
	<ul class="list-group">
		@foreach ($topics as $topic)
			<li class="list-group-item">
				<a href="{{ $topic->link() }}">
					{{ $topic->title }}
				</a>

				<span class="meta pull-right">
					{{ $topic->reply_count }}回复
					<span>·</span>
					{{ $topic->created_at->diffForHumans() }}
				</span>
			</li>
		@endforeach
	</ul>

@else

   <div class="empty-block">暂无数据 ~_~ </div>

@endif

{!! $topics->render() !!}

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title', Auth::user()->name .'编辑资料')

@section('content')

<div class="container">
	<div class="panel panel-default col-md-10 col-md-offset-1">
		<div class="panel-heading">
			<h4>
				<i class="glyphicon glyphicon-edit"></i>{{ Auth::user()->name }} · 编辑个人资料
			</h4>

		</div>
		
		@include('common.error')

		<div class="panel-body">
			<form action="{{ route('users.update', $user->id) }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
				<input type="hidden" name="_method" value="PUT">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">

				<div class="form-group">
					<label for="name-field">用户名</label>
					<input id="name-field" class="form-control" type="text" name="name" value="{{ old('name', $user->name) }}">
				</div>

				<div class="form-group">
					<label for="email-field">电子邮箱</label>
					<input id="email-field" class="form-control" type="email" name="email" value="{{ old('email', $user->email) }}">
				</div>

				<div class="form-group">
					<label for="introduction-field">个人简介</label>
					<textarea id="introduction-field" class="form-control" name="introduction" rows="3">
						{{ old('introduction', $user->introduction) }}
					</textarea>
				</div>

				<div class="form-group">
					<label for="" class="avatar-label">用户头像</label>
					<input type="file" name="avatar">

					@if ($user->avatar)
						<hr>
						<img class="thumbnail img-responsive" src="{{ $user->avatar }}" width="200">
					@endif

				</div>

				<div class="well well-sm">
					<button class="btn btn-primary" type="submit">保存</button>
				</div>
			</form>
		</div>
	</div>
</div>

@stop

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title', $user->name . '个人中心')

@section('content')
<div class="row">
	<div class="col-lg-3 col-md-3 hidden-sm hidden-xs user-info">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="media">
					<div class="center">
						<img class="thumbnail img-responsive" src="{{ $user->avatar }}" width="300px" height="300px">
					</div>
					<div class="media-body">
						<hr>
						<h4>
							<strong>个人简介</strong>
						</h4>
						<p>
							{{ $user->introduction }}
						</p>
						<hr>
                        <h4><strong>注册于</strong></h4>
                        <p>{{ $user->created_at->diffForHumans() }}</p>
                        <hr>
                        <h4><strong>最后活跃</strong></h4>
                        <p title="{{  $user->last_actived_at }}">{{ $user->last_actived_at->diffForHumans() }}</p>						
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-9 col-md-9 col-sm-12 col-xs-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <span>
                    <h1 class="panel-title pull-left" style="font-size:30px;">{{ $user->name }} <small>{{ $user->email }}</small></h1>
                </span>
            </div>
        </div>
        <hr>

        {{-- 用户发布的内容 --}}
        <div class="panel panel-default">
            <div class="panel-body">
                <ul class="nav nav-tabs">
                	<li class="{{ active_class(if_query('tab', null)) }}">
                		<a href="{{ route('users.show', $user->id) }}">TA的话题</a>
                	</li>
                	<li class="{{ active_class(if_query('tab', 'replies')) }}">
                		<a href="{{ route('users.show', [$user->id, 'tab' => 'replies']) }}">TA的回复</a>
                	</li>
                </ul>
                @if (if_query('tab','replies'))
                    @include('users._replies', ['replies' => $user->replies()->with('topic')->recent()->paginate(5)])
                @else
                    @include('users._topics', ['topics' => $user->topics()->recent()->paginate(5)])
                @endif
                
            </div>
        </div>
    </div>
</div>

@stop